# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"

    config.vm.synced_folder "apps/", "/apps", create: true
    config.vm.provision "docker"
    config.vm.provision "shell", inline:
        "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"

    [2403, 27017].each do |port|
        config.vm.network :forwarded_port, guest: port, host: port, auto_correct: true
    end

end
